var annotated_dup =
[
    [ "Myth", "namespaceMyth.html", [
      [ "Control", "classMyth_1_1Control.html", "classMyth_1_1Control" ],
      [ "SubscriptionHandlerThread", "classMyth_1_1SubscriptionHandlerThread.html", null ],
      [ "BasicEventHandler", "classMyth_1_1BasicEventHandler.html", null ],
      [ "EventSubscriber", "classMyth_1_1EventSubscriber.html", null ],
      [ "EventHandler", "classMyth_1_1EventHandler.html", "classMyth_1_1EventHandler" ],
      [ "FilePlayback", "classMyth_1_1FilePlayback.html", null ],
      [ "LiveTVPlayback", "classMyth_1_1LiveTVPlayback.html", null ],
      [ "Lockable", "classMyth_1_1Lockable.html", "classMyth_1_1Lockable" ],
      [ "Locked", "classMyth_1_1Locked.html", "classMyth_1_1Locked" ],
      [ "RecordingPlayback", "classMyth_1_1RecordingPlayback.html", null ],
      [ "shared_ptr_base", "classMyth_1_1shared__ptr__base.html", null ],
      [ "shared_ptr", "classMyth_1_1shared__ptr.html", null ],
      [ "Stream", "classMyth_1_1Stream.html", null ],
      [ "ItemList", "structMyth_1_1ItemList.html", null ],
      [ "Version", "structMyth_1_1Version.html", null ],
      [ "Setting", "structMyth_1_1Setting.html", null ],
      [ "Artwork", "structMyth_1_1Artwork.html", null ],
      [ "Channel", "structMyth_1_1Channel.html", null ],
      [ "Recording", "structMyth_1_1Recording.html", null ],
      [ "Program", "structMyth_1_1Program.html", null ],
      [ "CaptureCard", "structMyth_1_1CaptureCard.html", null ],
      [ "CardInput", "structMyth_1_1CardInput.html", null ],
      [ "VideoSource", "structMyth_1_1VideoSource.html", null ],
      [ "RecordSchedule", "structMyth_1_1RecordSchedule.html", null ],
      [ "SignalStatus", "structMyth_1_1SignalStatus.html", null ],
      [ "EventMessage", "structMyth_1_1EventMessage.html", null ],
      [ "StorageGroupFile", "structMyth_1_1StorageGroupFile.html", null ],
      [ "Mark", "structMyth_1_1Mark.html", null ],
      [ "WSServiceVersion_t", "structMyth_1_1WSServiceVersion__t.html", null ],
      [ "WSAPI", "classMyth_1_1WSAPI.html", "classMyth_1_1WSAPI" ],
      [ "WSStream", "classMyth_1_1WSStream.html", null ],
      [ "ProtoBase", "classMyth_1_1ProtoBase.html", "classMyth_1_1ProtoBase" ],
      [ "ProtoEvent", "classMyth_1_1ProtoEvent.html", "classMyth_1_1ProtoEvent" ],
      [ "ProtoMonitor", "classMyth_1_1ProtoMonitor.html", "classMyth_1_1ProtoMonitor" ],
      [ "ProtoPlayback", "classMyth_1_1ProtoPlayback.html", null ],
      [ "ProtoRecorder", "classMyth_1_1ProtoRecorder.html", null ],
      [ "ProtoTransfer", "classMyth_1_1ProtoTransfer.html", "classMyth_1_1ProtoTransfer" ]
    ] ],
    [ "NSROOT", null, [
      [ "JSON", "namespaceNSROOT_1_1JSON.html", [
        [ "Node", "classNSROOT_1_1JSON_1_1Node.html", null ],
        [ "Document", "classNSROOT_1_1JSON_1_1Document.html", null ]
      ] ],
      [ "OS", null, [
        [ "Atomic", "classNSROOT_1_1OS_1_1Atomic.html", null ],
        [ "Condition", "classNSROOT_1_1OS_1_1Condition.html", null ],
        [ "Event", "classNSROOT_1_1OS_1_1Event.html", null ],
        [ "Latch", "classNSROOT_1_1OS_1_1Latch.html", "classNSROOT_1_1OS_1_1Latch" ],
        [ "ReadLock", "classNSROOT_1_1OS_1_1ReadLock.html", "classNSROOT_1_1OS_1_1ReadLock" ],
        [ "WriteLock", "classNSROOT_1_1OS_1_1WriteLock.html", null ],
        [ "Mutex", "classNSROOT_1_1OS_1_1Mutex.html", null ],
        [ "LockGuard", "classNSROOT_1_1OS_1_1LockGuard.html", null ],
        [ "Thread", "classNSROOT_1_1OS_1_1Thread.html", "classNSROOT_1_1OS_1_1Thread" ],
        [ "ThreadPool", "classNSROOT_1_1OS_1_1ThreadPool.html", null ],
        [ "Worker", "classNSROOT_1_1OS_1_1Worker.html", null ],
        [ "WorkerThread", "classNSROOT_1_1OS_1_1WorkerThread.html", null ],
        [ "Timeout", "classNSROOT_1_1OS_1_1Timeout.html", null ]
      ] ],
      [ "Compressor", "classNSROOT_1_1Compressor.html", "classNSROOT_1_1Compressor" ],
      [ "Decompressor", "classNSROOT_1_1Decompressor.html", "classNSROOT_1_1Decompressor" ],
      [ "RingBufferPacket", "classNSROOT_1_1RingBufferPacket.html", null ],
      [ "RingBuffer", "classNSROOT_1_1RingBuffer.html", "classNSROOT_1_1RingBuffer" ],
      [ "SSLSessionFactory", "classNSROOT_1_1SSLSessionFactory.html", "classNSROOT_1_1SSLSessionFactory" ],
      [ "SSLServerContext", "classNSROOT_1_1SSLServerContext.html", "classNSROOT_1_1SSLServerContext" ],
      [ "SecureSocket", "classNSROOT_1_1SecureSocket.html", "classNSROOT_1_1SecureSocket" ],
      [ "SocketAddress", "structNSROOT_1_1SocketAddress.html", null ],
      [ "NetSocket", "classNSROOT_1_1NetSocket.html", null ],
      [ "TcpSocket", "classNSROOT_1_1TcpSocket.html", "classNSROOT_1_1TcpSocket" ],
      [ "TcpServerSocket", "classNSROOT_1_1TcpServerSocket.html", "classNSROOT_1_1TcpServerSocket" ],
      [ "UdpSocket", "classNSROOT_1_1UdpSocket.html", "classNSROOT_1_1UdpSocket" ],
      [ "UdpServerSocket", "classNSROOT_1_1UdpServerSocket.html", "classNSROOT_1_1UdpServerSocket" ],
      [ "URIParser", "classNSROOT_1_1URIParser.html", "classNSROOT_1_1URIParser" ],
      [ "WSHeader", "classNSROOT_1_1WSHeader.html", null ],
      [ "WSRequestStreamSink", "classNSROOT_1_1WSRequestStreamSink.html", null ],
      [ "WSRequest", "classNSROOT_1_1WSRequest.html", null ],
      [ "WSResponse", "classNSROOT_1_1WSResponse.html", "classNSROOT_1_1WSResponse" ]
    ] ],
    [ "sajson", null, [
      [ "string", "classsajson_1_1string.html", null ],
      [ "literal", "classsajson_1_1literal.html", null ],
      [ "object_key_record", "structsajson_1_1object__key__record.html", null ],
      [ "object_key_comparator", "structsajson_1_1object__key__comparator.html", null ],
      [ "refcount", "classsajson_1_1refcount.html", null ],
      [ "mutable_string_view", "classsajson_1_1mutable__string__view.html", null ],
      [ "integer_storage", "unionsajson_1_1integer__storage.html", null ],
      [ "double_storage", "unionsajson_1_1double__storage.html", null ],
      [ "value", "classsajson_1_1value.html", null ],
      [ "document", "classsajson_1_1document.html", null ],
      [ "parser", "classsajson_1_1parser.html", "classsajson_1_1parser" ]
    ] ],
    [ "_pthread_cleanup", "struct__pthread__cleanup.html", null ],
    [ "_pthread_v", "struct__pthread__v.html", null ],
    [ "attr_bind_t", "structattr__bind__t.html", "structattr__bind__t" ],
    [ "autoptr", "classautoptr.html", null ],
    [ "bindings_t", "structbindings__t.html", "structbindings__t" ],
    [ "BUILTIN_BUFFER", "structBUILTIN__BUFFER.html", null ],
    [ "debug_ctx_t", "structdebug__ctx__t.html", null ],
    [ "imaxdiv_t", "structimaxdiv__t.html", null ],
    [ "myth_protomap_t", "structmyth__protomap__t.html", null ],
    [ "protoref_t", "structprotoref__t.html", null ],
    [ "pthread_attr_t", "structpthread__attr__t.html", null ],
    [ "pthread_barrier_t", "structpthread__barrier__t.html", null ],
    [ "timespec", "structtimespec.html", null ],
    [ "timezone", "structtimezone.html", null ],
    [ "tz_t", "structtz__t.html", null ],
    [ "WS_CENCODING_TABLE", "structWS__CENCODING__TABLE.html", null ],
    [ "WS_CTYPE_TABLE", "structWS__CTYPE__TABLE.html", null ],
    [ "WS_HEADER_TABLE", "structWS__HEADER__TABLE.html", null ],
    [ "WS_METHOD_TABLE", "structWS__METHOD__TABLE.html", null ],
    [ "WS_STATUS_TABLE", "structWS__STATUS__TABLE.html", null ]
];