var annotated_dup =
[
    [ "Myth", "namespaceMyth.html", "namespaceMyth" ],
    [ "NSROOT", null, [
      [ "JSON", "namespaceNSROOT_1_1JSON.html", "namespaceNSROOT_1_1JSON" ],
      [ "OS", null, [
        [ "CCondition", "classNSROOT_1_1OS_1_1CCondition.html", "classNSROOT_1_1OS_1_1CCondition" ],
        [ "CEvent", "classNSROOT_1_1OS_1_1CEvent.html", "classNSROOT_1_1OS_1_1CEvent" ],
        [ "CLockGuard", "classNSROOT_1_1OS_1_1CLockGuard.html", "classNSROOT_1_1OS_1_1CLockGuard" ],
        [ "CMutex", "classNSROOT_1_1OS_1_1CMutex.html", "classNSROOT_1_1OS_1_1CMutex" ],
        [ "CThread", "classNSROOT_1_1OS_1_1CThread.html", "classNSROOT_1_1OS_1_1CThread" ],
        [ "CThreadPool", "classNSROOT_1_1OS_1_1CThreadPool.html", "classNSROOT_1_1OS_1_1CThreadPool" ],
        [ "CTimeout", "classNSROOT_1_1OS_1_1CTimeout.html", "classNSROOT_1_1OS_1_1CTimeout" ],
        [ "CWorker", "classNSROOT_1_1OS_1_1CWorker.html", "classNSROOT_1_1OS_1_1CWorker" ],
        [ "CWorkerThread", "classNSROOT_1_1OS_1_1CWorkerThread.html", "classNSROOT_1_1OS_1_1CWorkerThread" ]
      ] ],
      [ "Compressor", "classNSROOT_1_1Compressor.html", "classNSROOT_1_1Compressor" ],
      [ "Decompressor", "classNSROOT_1_1Decompressor.html", "classNSROOT_1_1Decompressor" ],
      [ "NetSocket", "classNSROOT_1_1NetSocket.html", "classNSROOT_1_1NetSocket" ],
      [ "SecureSocket", "classNSROOT_1_1SecureSocket.html", "classNSROOT_1_1SecureSocket" ],
      [ "SocketAddress", "structNSROOT_1_1SocketAddress.html", "structNSROOT_1_1SocketAddress" ],
      [ "SSLSessionFactory", "classNSROOT_1_1SSLSessionFactory.html", "classNSROOT_1_1SSLSessionFactory" ],
      [ "TcpServerSocket", "classNSROOT_1_1TcpServerSocket.html", "classNSROOT_1_1TcpServerSocket" ],
      [ "TcpSocket", "classNSROOT_1_1TcpSocket.html", "classNSROOT_1_1TcpSocket" ],
      [ "UdpSocket", "classNSROOT_1_1UdpSocket.html", "classNSROOT_1_1UdpSocket" ],
      [ "URIParser", "classNSROOT_1_1URIParser.html", "classNSROOT_1_1URIParser" ],
      [ "WSRequest", "classNSROOT_1_1WSRequest.html", "classNSROOT_1_1WSRequest" ],
      [ "WSResponse", "classNSROOT_1_1WSResponse.html", "classNSROOT_1_1WSResponse" ]
    ] ],
    [ "sajson", null, [
      [ "document", "classsajson_1_1document.html", "classsajson_1_1document" ],
      [ "double_storage", "unionsajson_1_1double__storage.html", "unionsajson_1_1double__storage" ],
      [ "integer_storage", "unionsajson_1_1integer__storage.html", "unionsajson_1_1integer__storage" ],
      [ "literal", "classsajson_1_1literal.html", "classsajson_1_1literal" ],
      [ "mutable_string_view", "classsajson_1_1mutable__string__view.html", "classsajson_1_1mutable__string__view" ],
      [ "object_key_comparator", "structsajson_1_1object__key__comparator.html", "structsajson_1_1object__key__comparator" ],
      [ "object_key_record", "structsajson_1_1object__key__record.html", "structsajson_1_1object__key__record" ],
      [ "parser", "classsajson_1_1parser.html", "classsajson_1_1parser" ],
      [ "refcount", "classsajson_1_1refcount.html", "classsajson_1_1refcount" ],
      [ "string", "classsajson_1_1string.html", "classsajson_1_1string" ],
      [ "value", "classsajson_1_1value.html", "classsajson_1_1value" ]
    ] ],
    [ "_pthread_cleanup", "struct__pthread__cleanup.html", "struct__pthread__cleanup" ],
    [ "_pthread_v", "struct__pthread__v.html", "struct__pthread__v" ],
    [ "attr_bind_t", "structattr__bind__t.html", "structattr__bind__t" ],
    [ "bindings_t", "structbindings__t.html", "structbindings__t" ],
    [ "debug_ctx_t", "structdebug__ctx__t.html", "structdebug__ctx__t" ],
    [ "imaxdiv_t", "structimaxdiv__t.html", "structimaxdiv__t" ],
    [ "mimetype", "structmimetype.html", "structmimetype" ],
    [ "myth_protomap_t", "structmyth__protomap__t.html", "structmyth__protomap__t" ],
    [ "protoref_t", "structprotoref__t.html", "structprotoref__t" ],
    [ "pthread_attr_t", "structpthread__attr__t.html", "structpthread__attr__t" ],
    [ "pthread_barrier_t", "structpthread__barrier__t.html", "structpthread__barrier__t" ],
    [ "timespec", "structtimespec.html", "structtimespec" ]
];