CppMyth (developer): Myth::ProtoBase Class Reference
Myth::ProtoBase Class Reference abstract
Public Member Functions
ProtoBase (const std::string &server, unsigned port)
virtual bool Open ()=0
virtual void Close ()
virtual bool IsOpen ()
virtual unsigned GetProtoVersion () const
virtual std::string GetServer () const
virtual unsigned GetPort () const
virtual int GetSocketErrNo () const
virtual int GetSocket () const
virtual bool HasHanging () const
virtual void CleanHanging ()
Protected Member Functions
bool OpenConnection (int rcvbuf)
void HangException ()
bool SendCommand (const char *cmd, bool feedback=true)
size_t GetMessageLength () const
bool ReadField (std::string &field)
bool IsMessageOK (const std::string &field) const
size_t FlushMessage ()
bool RcvMessageLength ()
ProgramPtr RcvProgramInfo ()
void MakeProgramInfo (const Program &program, std::string &msg)
Protected Attributes
PLATFORM::CMutex * m_mutex
TcpSocket * m_socket
unsigned m_protoVersion
std::string m_server
unsigned m_port
bool m_hang
Connection hang: while true allow retry.
bool m_tainted
Connection has hung since last reset.
size_t m_msgLength
size_t m_msgConsumed
Private Member Functions
bool RcvVersion (unsigned *version)
ProgramPtr RcvProgramInfo75 ()
ProgramPtr RcvProgramInfo76 ()
ProgramPtr RcvProgramInfo79 ()
ProgramPtr RcvProgramInfo82 ()
void MakeProgramInfo75 (const Program &program, std::string &msg)
void MakeProgramInfo76 (const Program &program, std::string &msg)
void MakeProgramInfo79 (const Program &program, std::string &msg)
void MakeProgramInfo82 (const Program &program, std::string &msg)
Private Attributes
bool m_isOpen
Detailed Description
Definition at line 44 of file mythprotobase.h.
Member Function Documentation
bool ProtoBase::RcvVersion (unsigned * version) private
Parse feedback of command MYTH_PROTO_VERSION and return protocol version of backend
Parameters
version
Returns
true : false
Definition at line 243 of file mythprotobase.cpp.
References ReadField().
bool ProtoBase::ReadField (std::string & field) protected
Read one field from the backend response
Parameters
field
Returns
true : false
Definition at line 124 of file mythprotobase.cpp.
Referenced by Myth::ProtoEvent::RcvBackendMessage(), and RcvVersion().
The documentation for this class was generated from the following files:
/home/jlb/src/janbar/cppmythlib/cppmyth/src/proto/mythprotobase.h
/home/jlb/src/janbar/cppmythlib/cppmyth/src/proto/mythprotobase.cpp