CPPMyth: NSROOT::Decompressor Class Reference
NSROOT::Decompressor Class Reference
Public Types
typedef int(* STREAM_READER) (void *handle, void *buf, int sz)
Public Member Functions
Decompressor (STREAM_READER reader, void *handle)
Decompressor (const char *input, size_t len)
bool HasOutputData ()
More data can be read from output stream.
bool IsCompleted ()
Output stream is completed.
bool HasBufferError ()
Data cannot be read from input.
bool HasStreamError ()
Data error occurred from stream.
size_t ReadOutput (char *buf, size_t len)
Copy data from output stream to the given pointer until size limit.
size_t FetchOutput (const char **data)
Fetch next chunk of data from output stream. No copy of data is performed and result can be used as is.
Private Types
enum { MEM_BUFFER, FCB_READER }
Private Member Functions
size_t NextChunk ()
Static Private Member Functions
static int _init (void *zp, void *out, size_t len)
Private Attributes
int m_status
bool m_stop
size_t m_chunk_size
enum NSROOT::Decompressor:: { ... } m_type_in
size_t m_input_len
const char * m_input
STREAM_READER m_rstream
void * m_rstream_hdl
char * m_rstream_buf
char * m_output
size_t m_output_pos
size_t m_output_len
void * _opaque
Detailed Description
Definition at line 112 of file compressor.h.
Member Function Documentation
size_t Decompressor::FetchOutput (const char ** data)
Fetch next chunk of data from output stream. No copy of data is performed and result can be used as is.
Parameters
data pointer to const data pointer
Returns
the byte count available from the pointer to const data
Definition at line 412 of file compressor.cpp.
bool Decompressor::HasBufferError ()
Data cannot be read from input.
Returns
Input status
Definition at line 347 of file compressor.cpp.
bool NSROOT::Decompressor::HasOutputData () inline
More data can be read from output stream.
Returns
Output status
Definition at line 125 of file compressor.h.
References NSROOT::Compressor::FetchOutput(), NSROOT::Compressor::HasBufferError(), NSROOT::Compressor::HasStreamError(), NSROOT::Compressor::IsCompleted(), and NSROOT::Compressor::ReadOutput().
bool Decompressor::HasStreamError ()
Data error occurred from stream.
Returns
stream status
Definition at line 352 of file compressor.cpp.
bool Decompressor::IsCompleted ()
Output stream is completed.
Returns
Output stream status
Definition at line 342 of file compressor.cpp.
size_t Decompressor::ReadOutput (char * buf, size_t len)
Copy data from output stream to the given pointer until size limit.
Parameters
buf pointer to copy data
len max length of data
Returns
lenght of copied data
Definition at line 365 of file compressor.cpp.
The documentation for this class was generated from the following files:
/home/jlb/src/janbar/PVR/cppmythlib/cppmyth/src/private/compressor.h
/home/jlb/src/janbar/PVR/cppmythlib/cppmyth/src/private/compressor.cpp