CppMyth (developer): Myth::Control Class Reference
Myth::Control Class Reference
Public Member Functions
Control (const std::string &server, unsigned protoPort, unsigned wsapiPort)
Control (const std::string &server, unsigned protoPort, unsigned wsapiPort, bool blockShutdown)
bool Open ()
void Close ()
bool IsOpen ()
bool HasHanging () const
void CleanHanging ()
unsigned CheckService ()
Check availability of API services.
std::string GetServerHostName ()
Query server host name.
VersionPtr GetVersion ()
Query server version infos.
bool QueryFreeSpaceSummary (int64_t *total, int64_t *used)
Queries the backend for free space summary.
bool QueryGenPixmap (const Program &program)
Triggers preview image generation on the backend for a specified show.
bool CancelNextRecording (int rnum, bool cancel)
Ask the backend to cancel/continue next recording.
SettingPtr GetSetting (const std::string &key, const std::string hostname)
Query setting by its key.
SettingPtr GetSetting (const std::string &key, bool myhost)
Query setting by its key.
SettingMapPtr GetSettings (const std::string hostname)
Query all settings.
SettingMapPtr GetSettings (bool myhost)
Query all settings.
bool PutSetting (const std::string &key, const std::string &value, bool myhost)
Put setting.
std::string GetBackendServerIP (const std::string &hostName)
Query backend server IP.
std::string GetBackendServerIP6 (const std::string &hostName)
Query backend server IP6.
unsigned GetBackendServerPort (const std::string &hostName)
Query backend server port for protocol commands.
ProgramListPtr GetRecordedList (unsigned n=0, bool descending=false)
Query information on all recorded programs.
ProgramPtr GetRecorded (uint32_t chanid, time_t recstartts)
Query information on a single item from recordings.
bool UpdateRecordedWatchedStatus (const Program &program, bool watched)
Update watched status for a recorded.
bool DeleteRecording (const Program &program, bool forceDelete=false, bool allowRerecord=false)
Remove a Recording from the database and disk.
bool UndeleteRecording (const Program &program)
bool StopRecording (const Program &program)
CaptureCardListPtr GetCaptureCardList ()
Get all configured capture devices.
VideoSourceListPtr GetVideoSourceList ()
Get all video sources.
ChannelListPtr GetChannelList (uint32_t sourceid, bool onlyVisible=true)
Get all configured channels for a video source.
ProgramMapPtr GetProgramGuide (uint32_t chanid, time_t starttime, time_t endtime)
Query the guide information for a particular time period and a channel.
RecordScheduleListPtr GetRecordScheduleList ()
Query all configured recording rules.
RecordSchedulePtr GetRecordSchedule (uint32_t recordid)
Get a single recording rule, by record id.
bool AddRecordSchedule (RecordSchedule &record)
Add a new recording rule.
bool UpdateRecordSchedule (RecordSchedule &record)
Update a recording rule.
bool DisableRecordSchedule (uint32_t recordid)
Disable a recording rule.
bool EnableRecordSchedule (uint32_t recordid)
Enable a recording rule.
bool RemoveRecordSchedule (uint32_t recordid)
Remove a recording rule.
ProgramListPtr GetUpcomingList ()
Query information on all upcoming programs matching recording rules.
ProgramListPtr GetConflictList ()
Query information on upcoming items which will not record due to conflicts.
ProgramListPtr GetExpiringList ()
Query information on recorded programs which are set to expire.
WSStreamPtr GetFile (const std::string &filename, const std::string &sgname)
Download a given file from a given storage group.
WSStreamPtr GetChannelIcon (uint32_t chanid, unsigned width=0, unsigned height=0)
Get the icon file for a given channel.
WSStreamPtr GetPreviewImage (const Program &program, unsigned width=0, unsigned height=0)
Get, and optionally scale, an preview thumbnail for a given recording by timestamp, chanid and starttime.
WSStreamPtr GetRecordingArtwork (const std::string &type, const Program &program, unsigned width=0, unsigned height=0)
Get, and optionally scale, an image file of a given type (coverart, banner, fanart) for a given recording's inetref and season number.
ArtworkListPtr GetRecordingArtworkList (uint32_t chanid, time_t recstartts)
Get a list of artwork available for a recording by start time and channel id.
bool RefreshRecordedArtwork (Program &program)
Refresh artwork available for a recording.
MarkListPtr GetCutList (const Program &program, int unit=0)
Request a set of cut list marks for a recording.
MarkListPtr GetCommBreakList (const Program &program, int unit=0)
Request a set of commercial break marks for a recording.
bool BlockShutdown ()
Prevents backend from shutting down until a the next call to AllowShutdown().
bool AllowShutdown ()
Allows backend to shut down again after a previous call to BlockShutdown().
Private Attributes
ProtoMonitor m_monitor
WSAPI m_wsapi
Detailed Description
Definition at line 32 of file mythcontrol.h.
Member Function Documentation
bool Myth::Control::AddRecordSchedule (RecordSchedule & record) inline
Add a new recording rule.
Parameters
record
Returns
status. On success Id is updated with the new.
Definition at line 305 of file mythcontrol.h.
References Myth::WSAPI::AddRecordSchedule().
bool Myth::Control::AllowShutdown () inline
Allows backend to shut down again after a previous call to BlockShutdown().
Returns
bool
Definition at line 478 of file mythcontrol.h.
bool Myth::Control::BlockShutdown () inline
Prevents backend from shutting down until a the next call to AllowShutdown().
Returns
bool
Definition at line 469 of file mythcontrol.h.
bool Myth::Control::CancelNextRecording (int rnum, bool cancel) inline
Ask the backend to cancel/continue next recording.
Parameters
rnum recorder Id
cancel
Returns
bool
Definition at line 99 of file mythcontrol.h.
unsigned Myth::Control::CheckService () inline
Check availability of API services.
Returns
If unavailable then 0 else the backend protocol number
Definition at line 49 of file mythcontrol.h.
bool Myth::Control::DeleteRecording (const Program & program, bool forceDelete = false, bool allowRerecord = false) inline
Remove a Recording from the database and disk.
Parameters
program
forceDelete (default false)
allowRerecord (default false)
Returns
bool
Definition at line 219 of file mythcontrol.h.
References Myth::WSAPI::DeleteRecording().
bool Myth::Control::DisableRecordSchedule (uint32_t recordid) inline
Disable a recording rule.
Parameters
recordid
Returns
status
Definition at line 325 of file mythcontrol.h.
References Myth::WSAPI::DisableRecordSchedule().
bool Myth::Control::EnableRecordSchedule (uint32_t recordid) inline
Enable a recording rule.
Parameters
recordid
Returns
status
Definition at line 335 of file mythcontrol.h.
References Myth::WSAPI::EnableRecordSchedule().
std::string Control::GetBackendServerIP (const std::string & hostName)
Query backend server IP.
Parameters
hostName
Returns
string containing found IP or nil
Definition at line 57 of file mythcontrol.cpp.
References GetSetting().
std::string Control::GetBackendServerIP6 (const std::string & hostName)
Query backend server IP6.
Parameters
hostName
Returns
string containing found IP6 or nil
Definition at line 67 of file mythcontrol.cpp.
References GetSetting().
unsigned Control::GetBackendServerPort (const std::string & hostName)
Query backend server port for protocol commands.
Parameters
hostName
Returns
unsigned more than 0 else invalid
Definition at line 77 of file mythcontrol.cpp.
References GetSetting().
CaptureCardListPtr Myth::Control::GetCaptureCardList () inline
Get all configured capture devices.
Returns
CaptureCardListPtr
Definition at line 244 of file mythcontrol.h.
References Myth::WSAPI::GetCaptureCardList().
WSStreamPtr Myth::Control::GetChannelIcon (uint32_t chanid, unsigned width = 0, unsigned height = 0) inline
Get the icon file for a given channel.
Parameters
chanid
width (default 0)
height (default 0)
Returns
WSStreamPtr
Definition at line 395 of file mythcontrol.h.
References Myth::WSAPI::GetChannelIcon().
ChannelListPtr Myth::Control::GetChannelList (uint32_t sourceid, bool onlyVisible = true) inline
Get all configured channels for a video source.
Parameters
sourceid
onlyVisible (default true)
Returns
ChannelListPtr
Definition at line 264 of file mythcontrol.h.
References Myth::WSAPI::GetChannelList().
MarkListPtr Myth::Control::GetCommBreakList (const Program & program, int unit = 0) inline
Request a set of commercial break marks for a recording.
Parameters
program
unit 0 = Frame count, 1 = Position, 2 = Duration ms
Returns
MarkListPtr
Definition at line 460 of file mythcontrol.h.
ProgramListPtr Myth::Control::GetConflictList () inline
Query information on upcoming items which will not record due to conflicts.
Returns
ProgramListPtr
Definition at line 363 of file mythcontrol.h.
References Myth::WSAPI::GetConflictList().
MarkListPtr Myth::Control::GetCutList (const Program & program, int unit = 0) inline
Request a set of cut list marks for a recording.
Parameters
program
unit 0 = Frame count, 1 = Position, 2 = Duration ms
Returns
MarkListPtr
Definition at line 449 of file mythcontrol.h.
ProgramListPtr Myth::Control::GetExpiringList () inline
Query information on recorded programs which are set to expire.
Returns
ProgramListPtr
Definition at line 372 of file mythcontrol.h.
References Myth::WSAPI::GetExpiringList().
WSStreamPtr Myth::Control::GetFile (const std::string & filename, const std::string & sgname) inline
Download a given file from a given storage group.
Parameters
filename
sgname
Returns
WSStreamPtr
Definition at line 383 of file mythcontrol.h.
References Myth::WSAPI::GetFile().
WSStreamPtr Myth::Control::GetPreviewImage (const Program & program, unsigned width = 0, unsigned height = 0) inline
Get, and optionally scale, an preview thumbnail for a given recording by timestamp, chanid and starttime.
Parameters
program
width (default 0)
height (default 0)
Returns
WSStreamPtr
Definition at line 407 of file mythcontrol.h.
References Myth::WSAPI::GetPreviewImage().
ProgramMapPtr Myth::Control::GetProgramGuide (uint32_t chanid, time_t starttime, time_t endtime) inline
Query the guide information for a particular time period and a channel.
Parameters
chanid
starttime
endtime
Returns
ProgramMapPtr
Definition at line 276 of file mythcontrol.h.
References Myth::WSAPI::GetProgramGuide().
ProgramPtr Myth::Control::GetRecorded (uint32_t chanid, time_t recstartts) inline
Query information on a single item from recordings.
Parameters
chanid
recstartts
Returns
ProgramPtr
Definition at line 196 of file mythcontrol.h.
References Myth::WSAPI::GetRecorded().
ProgramListPtr Myth::Control::GetRecordedList (unsigned n = 0, bool descending = false) inline
Query information on all recorded programs.
Parameters
n
descending
Returns
ProgramListPtr
Definition at line 185 of file mythcontrol.h.
References Myth::WSAPI::GetRecordedList().
WSStreamPtr Myth::Control::GetRecordingArtwork (const std::string & type, const Program & program, unsigned width = 0, unsigned height = 0) inline
Get, and optionally scale, an image file of a given type (coverart, banner, fanart) for a given recording's inetref and season number.
Parameters
type
program
width (default 0)
height (default 0)
Returns
WSStreamPtr
Definition at line 420 of file mythcontrol.h.
References Myth::WSAPI::GetRecordingArtwork().
ArtworkListPtr Myth::Control::GetRecordingArtworkList (uint32_t chanid, time_t recstartts) inline
Get a list of artwork available for a recording by start time and channel id.
Parameters
chanid
recstartts
Returns
ArtworkListPtr
Definition at line 431 of file mythcontrol.h.
References Myth::WSAPI::GetRecordingArtworkList().
Referenced by RefreshRecordedArtwork().
RecordSchedulePtr Myth::Control::GetRecordSchedule (uint32_t recordid) inline
Get a single recording rule, by record id.
Parameters
recordid
Returns
RecordSchedulePtr
Definition at line 295 of file mythcontrol.h.
References Myth::WSAPI::GetRecordSchedule().
RecordScheduleListPtr Myth::Control::GetRecordScheduleList () inline
Query all configured recording rules.
Returns
RecordScheduleListPtr
Definition at line 285 of file mythcontrol.h.
References Myth::WSAPI::GetRecordScheduleList().
std::string Myth::Control::GetServerHostName () inline
Query server host name.
Returns
string
Definition at line 58 of file mythcontrol.h.
SettingPtr Myth::Control::GetSetting (const std::string & key, const std::string hostname) inline
Query setting by its key.
Parameters
key
hostname
Returns
SettingPtr
Definition at line 110 of file mythcontrol.h.
References Myth::WSAPI::GetSetting().
Referenced by GetBackendServerIP(), GetBackendServerIP6(), and GetBackendServerPort().
SettingPtr Myth::Control::GetSetting (const std::string & key, bool myhost) inline
Query setting by its key.
Parameters
key
myhost
Returns
SettingPtr
Definition at line 121 of file mythcontrol.h.
References Myth::WSAPI::GetSetting().
SettingMapPtr Myth::Control::GetSettings (const std::string hostname) inline
Query all settings.
Parameters
hostname
Returns
SettingMapPtr
Definition at line 131 of file mythcontrol.h.
References Myth::WSAPI::GetSettings().
SettingMapPtr Myth::Control::GetSettings (bool myhost) inline
Query all settings.
Parameters
myhost
Returns
SettingMapPtr
Definition at line 141 of file mythcontrol.h.
References Myth::WSAPI::GetSettings().
ProgramListPtr Myth::Control::GetUpcomingList () inline
Query information on all upcoming programs matching recording rules.
Returns
ProgramListPtr
Definition at line 354 of file mythcontrol.h.
References Myth::WSAPI::GetUpcomingList().
VersionPtr Myth::Control::GetVersion () inline
Query server version infos.
Returns
VersionPtr
Definition at line 67 of file mythcontrol.h.
VideoSourceListPtr Myth::Control::GetVideoSourceList () inline
Get all video sources.
Returns
VideoSourceListPtr
Definition at line 253 of file mythcontrol.h.
References Myth::WSAPI::GetVideoSourceList().
bool Myth::Control::PutSetting (const std::string & key, const std::string & value, bool myhost) inline
Put setting.
Parameters
key
value
myhost
Returns
bool
Definition at line 153 of file mythcontrol.h.
References Myth::WSAPI::PutSetting().
bool Myth::Control::QueryFreeSpaceSummary (int64_t * total, int64_t * used) inline
Queries the backend for free space summary.
Parameters
total
used
Returns
bool
Definition at line 78 of file mythcontrol.h.
bool Myth::Control::QueryGenPixmap (const Program & program) inline
Triggers preview image generation on the backend for a specified show.
Parameters
program
Returns
bool
Definition at line 88 of file mythcontrol.h.
bool Control::RefreshRecordedArtwork (Program & program)
Refresh artwork available for a recording.
Parameters
program
Returns
bool Return true if any artwork found
Definition at line 87 of file mythcontrol.cpp.
References GetRecordingArtworkList().
bool Myth::Control::RemoveRecordSchedule (uint32_t recordid) inline
Remove a recording rule.
Parameters
recordid
Returns
status
Definition at line 345 of file mythcontrol.h.
References Myth::WSAPI::RemoveRecordSchedule().
bool Myth::Control::UpdateRecordedWatchedStatus (const Program & program, bool watched) inline
Update watched status for a recorded.
Parameters
chanid
recstartts
Returns
bool
Definition at line 207 of file mythcontrol.h.
References Myth::WSAPI::UpdateRecordedWatchedStatus().
bool Myth::Control::UpdateRecordSchedule (RecordSchedule & record) inline
Update a recording rule.
Parameters
record
Returns
status
Definition at line 315 of file mythcontrol.h.
References Myth::WSAPI::UpdateRecordSchedule().
The documentation for this class was generated from the following files:
/home/jlb/src/janbar/cppmythlib/cppmyth/src/mythcontrol.h
/home/jlb/src/janbar/cppmythlib/cppmyth/src/mythcontrol.cpp